# Generated by Django 4.0.5 on 2022-08-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=30)),
                ('profile', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=35)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
            ],
        ),
    ]
