# Generated by Django 4.0.5 on 2022-08-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberInBuilt', '0002_alter_staff_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
