# Generated by Django 4.0.5 on 2022-09-06 11:59

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cyberInBuilt', '0003_alter_staff_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=260)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.CharField(max_length=13)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('slug', models.CharField(max_length=120)),
                ('image', models.ImageField(default='default', upload_to='')),
            ],
        ),
    ]
